/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.pascal.pascal.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.pascal.pascal.PascalPackage;
import org.xtext.example.pascal.pascal.index_type;
import org.xtext.example.pascal.pascal.simple_type;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>index type</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.pascal.pascal.impl.index_typeImpl#getSimple_type <em>Simple type</em>}</li>
 * </ul>
 *
 * @generated
 */
public class index_typeImpl extends MinimalEObjectImpl.Container implements index_type
{
  /**
   * The cached value of the '{@link #getSimple_type() <em>Simple type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSimple_type()
   * @generated
   * @ordered
   */
  protected simple_type simple_type;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected index_typeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PascalPackage.Literals.INDEX_TYPE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public simple_type getSimple_type()
  {
    return simple_type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSimple_type(simple_type newSimple_type, NotificationChain msgs)
  {
    simple_type oldSimple_type = simple_type;
    simple_type = newSimple_type;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PascalPackage.INDEX_TYPE__SIMPLE_TYPE, oldSimple_type, newSimple_type);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSimple_type(simple_type newSimple_type)
  {
    if (newSimple_type != simple_type)
    {
      NotificationChain msgs = null;
      if (simple_type != null)
        msgs = ((InternalEObject)simple_type).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PascalPackage.INDEX_TYPE__SIMPLE_TYPE, null, msgs);
      if (newSimple_type != null)
        msgs = ((InternalEObject)newSimple_type).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PascalPackage.INDEX_TYPE__SIMPLE_TYPE, null, msgs);
      msgs = basicSetSimple_type(newSimple_type, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PascalPackage.INDEX_TYPE__SIMPLE_TYPE, newSimple_type, newSimple_type));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PascalPackage.INDEX_TYPE__SIMPLE_TYPE:
        return basicSetSimple_type(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PascalPackage.INDEX_TYPE__SIMPLE_TYPE:
        return getSimple_type();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PascalPackage.INDEX_TYPE__SIMPLE_TYPE:
        setSimple_type((simple_type)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PascalPackage.INDEX_TYPE__SIMPLE_TYPE:
        setSimple_type((simple_type)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PascalPackage.INDEX_TYPE__SIMPLE_TYPE:
        return simple_type != null;
    }
    return super.eIsSet(featureID);
  }

} //index_typeImpl
