/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.pascal.pascal.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.pascal.pascal.PascalPackage;
import org.xtext.example.pascal.pascal.output_list;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>output list</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class output_listImpl extends MinimalEObjectImpl.Container implements output_list
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected output_listImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PascalPackage.Literals.OUTPUT_LIST;
  }

} //output_listImpl
