/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.pascal.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.xtext.example.pascal.ui.AbstractPascalUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@SuppressWarnings("all")
public class PascalUiModule extends AbstractPascalUiModule {
  public PascalUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
