/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.pascal.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor
import org.eclipse.ui.plugin.AbstractUIPlugin

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
class PascalUiModule extends AbstractPascalUiModule {
	
	new(AbstractUIPlugin plugin) {
		super(plugin)
	}
	
}
