/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.pascal.pascal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>actual procedure</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.pascal.pascal.actual_procedure#getProcedure_identifier <em>Procedure identifier</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.pascal.pascal.PascalPackage#getactual_procedure()
 * @model
 * @generated
 */
public interface actual_procedure extends EObject
{
  /**
   * Returns the value of the '<em><b>Procedure identifier</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Procedure identifier</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Procedure identifier</em>' containment reference.
   * @see #setProcedure_identifier(identifier)
   * @see org.xtext.example.pascal.pascal.PascalPackage#getactual_procedure_Procedure_identifier()
   * @model containment="true"
   * @generated
   */
  identifier getProcedure_identifier();

  /**
   * Sets the value of the '{@link org.xtext.example.pascal.pascal.actual_procedure#getProcedure_identifier <em>Procedure identifier</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Procedure identifier</em>' containment reference.
   * @see #getProcedure_identifier()
   * @generated
   */
  void setProcedure_identifier(identifier value);

} // actual_procedure
