/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.pascal.pascal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>bound specification</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.pascal.pascal.bound_specification#getIdentifier <em>Identifier</em>}</li>
 *   <li>{@link org.xtext.example.pascal.pascal.bound_specification#getIdentifier2 <em>Identifier2</em>}</li>
 *   <li>{@link org.xtext.example.pascal.pascal.bound_specification#getOrdinal_type_identifier <em>Ordinal type identifier</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.pascal.pascal.PascalPackage#getbound_specification()
 * @model
 * @generated
 */
public interface bound_specification extends EObject
{
  /**
   * Returns the value of the '<em><b>Identifier</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Identifier</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Identifier</em>' containment reference.
   * @see #setIdentifier(identifier)
   * @see org.xtext.example.pascal.pascal.PascalPackage#getbound_specification_Identifier()
   * @model containment="true"
   * @generated
   */
  identifier getIdentifier();

  /**
   * Sets the value of the '{@link org.xtext.example.pascal.pascal.bound_specification#getIdentifier <em>Identifier</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Identifier</em>' containment reference.
   * @see #getIdentifier()
   * @generated
   */
  void setIdentifier(identifier value);

  /**
   * Returns the value of the '<em><b>Identifier2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Identifier2</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Identifier2</em>' containment reference.
   * @see #setIdentifier2(identifier)
   * @see org.xtext.example.pascal.pascal.PascalPackage#getbound_specification_Identifier2()
   * @model containment="true"
   * @generated
   */
  identifier getIdentifier2();

  /**
   * Sets the value of the '{@link org.xtext.example.pascal.pascal.bound_specification#getIdentifier2 <em>Identifier2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Identifier2</em>' containment reference.
   * @see #getIdentifier2()
   * @generated
   */
  void setIdentifier2(identifier value);

  /**
   * Returns the value of the '<em><b>Ordinal type identifier</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ordinal type identifier</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ordinal type identifier</em>' containment reference.
   * @see #setOrdinal_type_identifier(ordinal_type_identifier)
   * @see org.xtext.example.pascal.pascal.PascalPackage#getbound_specification_Ordinal_type_identifier()
   * @model containment="true"
   * @generated
   */
  ordinal_type_identifier getOrdinal_type_identifier();

  /**
   * Sets the value of the '{@link org.xtext.example.pascal.pascal.bound_specification#getOrdinal_type_identifier <em>Ordinal type identifier</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ordinal type identifier</em>' containment reference.
   * @see #getOrdinal_type_identifier()
   * @generated
   */
  void setOrdinal_type_identifier(ordinal_type_identifier value);

} // bound_specification
