/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.pascal.pascal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>compiler defined directives</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.pascal.pascal.compiler_defined_directives#getProcedure_heading <em>Procedure heading</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.pascal.pascal.PascalPackage#getcompiler_defined_directives()
 * @model
 * @generated
 */
public interface compiler_defined_directives extends EObject
{
  /**
   * Returns the value of the '<em><b>Procedure heading</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Procedure heading</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Procedure heading</em>' containment reference.
   * @see #setProcedure_heading(procedure_heading)
   * @see org.xtext.example.pascal.pascal.PascalPackage#getcompiler_defined_directives_Procedure_heading()
   * @model containment="true"
   * @generated
   */
  procedure_heading getProcedure_heading();

  /**
   * Sets the value of the '{@link org.xtext.example.pascal.pascal.compiler_defined_directives#getProcedure_heading <em>Procedure heading</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Procedure heading</em>' containment reference.
   * @see #getProcedure_heading()
   * @generated
   */
  void setProcedure_heading(procedure_heading value);

} // compiler_defined_directives
