/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.pascal.pascal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>digit sequence</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.pascal.pascal.digit_sequence#getSign <em>Sign</em>}</li>
 *   <li>{@link org.xtext.example.pascal.pascal.digit_sequence#getUnsigned_digit_sequence <em>Unsigned digit sequence</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.pascal.pascal.PascalPackage#getdigit_sequence()
 * @model
 * @generated
 */
public interface digit_sequence extends EObject
{
  /**
   * Returns the value of the '<em><b>Sign</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sign</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sign</em>' attribute.
   * @see #setSign(String)
   * @see org.xtext.example.pascal.pascal.PascalPackage#getdigit_sequence_Sign()
   * @model
   * @generated
   */
  String getSign();

  /**
   * Sets the value of the '{@link org.xtext.example.pascal.pascal.digit_sequence#getSign <em>Sign</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sign</em>' attribute.
   * @see #getSign()
   * @generated
   */
  void setSign(String value);

  /**
   * Returns the value of the '<em><b>Unsigned digit sequence</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Unsigned digit sequence</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unsigned digit sequence</em>' attribute.
   * @see #setUnsigned_digit_sequence(String)
   * @see org.xtext.example.pascal.pascal.PascalPackage#getdigit_sequence_Unsigned_digit_sequence()
   * @model
   * @generated
   */
  String getUnsigned_digit_sequence();

  /**
   * Sets the value of the '{@link org.xtext.example.pascal.pascal.digit_sequence#getUnsigned_digit_sequence <em>Unsigned digit sequence</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unsigned digit sequence</em>' attribute.
   * @see #getUnsigned_digit_sequence()
   * @generated
   */
  void setUnsigned_digit_sequence(String value);

} // digit_sequence
