/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.pascal.pascal;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.pascal.pascal.expression#getSimple_expression <em>Simple expression</em>}</li>
 *   <li>{@link org.xtext.example.pascal.pascal.expression#getRelational_operator <em>Relational operator</em>}</li>
 *   <li>{@link org.xtext.example.pascal.pascal.expression#getExpression <em>Expression</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.pascal.pascal.PascalPackage#getexpression()
 * @model
 * @generated
 */
public interface expression extends output_value
{
  /**
   * Returns the value of the '<em><b>Simple expression</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.pascal.pascal.simple_expression}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Simple expression</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Simple expression</em>' containment reference list.
   * @see org.xtext.example.pascal.pascal.PascalPackage#getexpression_Simple_expression()
   * @model containment="true"
   * @generated
   */
  EList<simple_expression> getSimple_expression();

  /**
   * Returns the value of the '<em><b>Relational operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Relational operator</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Relational operator</em>' attribute.
   * @see #setRelational_operator(String)
   * @see org.xtext.example.pascal.pascal.PascalPackage#getexpression_Relational_operator()
   * @model
   * @generated
   */
  String getRelational_operator();

  /**
   * Sets the value of the '{@link org.xtext.example.pascal.pascal.expression#getRelational_operator <em>Relational operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Relational operator</em>' attribute.
   * @see #getRelational_operator()
   * @generated
   */
  void setRelational_operator(String value);

  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.pascal.pascal.expression}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expression</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference list.
   * @see org.xtext.example.pascal.pascal.PascalPackage#getexpression_Expression()
   * @model containment="true"
   * @generated
   */
  EList<expression> getExpression();

} // expression
