/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.pascal.pascal;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>fixed part</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.pascal.pascal.fixed_part#getRecord_section <em>Record section</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.pascal.pascal.PascalPackage#getfixed_part()
 * @model
 * @generated
 */
public interface fixed_part extends EObject
{
  /**
   * Returns the value of the '<em><b>Record section</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.pascal.pascal.record_section}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Record section</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Record section</em>' containment reference list.
   * @see org.xtext.example.pascal.pascal.PascalPackage#getfixed_part_Record_section()
   * @model containment="true"
   * @generated
   */
  EList<record_section> getRecord_section();

} // fixed_part
