/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.pascal.pascal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>function designator</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.pascal.pascal.function_designator#getFunction_identifier <em>Function identifier</em>}</li>
 *   <li>{@link org.xtext.example.pascal.pascal.function_designator#getActual_parameter_list <em>Actual parameter list</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.pascal.pascal.PascalPackage#getfunction_designator()
 * @model
 * @generated
 */
public interface function_designator extends EObject
{
  /**
   * Returns the value of the '<em><b>Function identifier</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Function identifier</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function identifier</em>' containment reference.
   * @see #setFunction_identifier(identifier)
   * @see org.xtext.example.pascal.pascal.PascalPackage#getfunction_designator_Function_identifier()
   * @model containment="true"
   * @generated
   */
  identifier getFunction_identifier();

  /**
   * Sets the value of the '{@link org.xtext.example.pascal.pascal.function_designator#getFunction_identifier <em>Function identifier</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Function identifier</em>' containment reference.
   * @see #getFunction_identifier()
   * @generated
   */
  void setFunction_identifier(identifier value);

  /**
   * Returns the value of the '<em><b>Actual parameter list</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Actual parameter list</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actual parameter list</em>' containment reference.
   * @see #setActual_parameter_list(actual_parameter_list)
   * @see org.xtext.example.pascal.pascal.PascalPackage#getfunction_designator_Actual_parameter_list()
   * @model containment="true"
   * @generated
   */
  actual_parameter_list getActual_parameter_list();

  /**
   * Sets the value of the '{@link org.xtext.example.pascal.pascal.function_designator#getActual_parameter_list <em>Actual parameter list</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Actual parameter list</em>' containment reference.
   * @see #getActual_parameter_list()
   * @generated
   */
  void setActual_parameter_list(actual_parameter_list value);

} // function_designator
