/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.pascal.pascal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>index type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.pascal.pascal.index_type#getSimple_type <em>Simple type</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.pascal.pascal.PascalPackage#getindex_type()
 * @model
 * @generated
 */
public interface index_type extends EObject
{
  /**
   * Returns the value of the '<em><b>Simple type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Simple type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Simple type</em>' containment reference.
   * @see #setSimple_type(simple_type)
   * @see org.xtext.example.pascal.pascal.PascalPackage#getindex_type_Simple_type()
   * @model containment="true"
   * @generated
   */
  simple_type getSimple_type();

  /**
   * Sets the value of the '{@link org.xtext.example.pascal.pascal.index_type#getSimple_type <em>Simple type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Simple type</em>' containment reference.
   * @see #getSimple_type()
   * @generated
   */
  void setSimple_type(simple_type value);

} // index_type
