/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.pascal.pascal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>integer number</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.pascal.pascal.integer_number#getDigit_sequence <em>Digit sequence</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.pascal.pascal.PascalPackage#getinteger_number()
 * @model
 * @generated
 */
public interface integer_number extends EObject
{
  /**
   * Returns the value of the '<em><b>Digit sequence</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Digit sequence</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Digit sequence</em>' containment reference.
   * @see #setDigit_sequence(digit_sequence)
   * @see org.xtext.example.pascal.pascal.PascalPackage#getinteger_number_Digit_sequence()
   * @model containment="true"
   * @generated
   */
  digit_sequence getDigit_sequence();

  /**
   * Sets the value of the '{@link org.xtext.example.pascal.pascal.integer_number#getDigit_sequence <em>Digit sequence</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Digit sequence</em>' containment reference.
   * @see #getDigit_sequence()
   * @generated
   */
  void setDigit_sequence(digit_sequence value);

} // integer_number
