/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.pascal.pascal;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Procedure</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.pascal.pascal.PascalPackage#getProcedure()
 * @model
 * @generated
 */
public interface Procedure extends Begin
{
} // Procedure
