/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.pascal.pascal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>repeat statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.pascal.pascal.repeat_statement#getStatement_sequence <em>Statement sequence</em>}</li>
 *   <li>{@link org.xtext.example.pascal.pascal.repeat_statement#getExpression <em>Expression</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.pascal.pascal.PascalPackage#getrepeat_statement()
 * @model
 * @generated
 */
public interface repeat_statement extends EObject
{
  /**
   * Returns the value of the '<em><b>Statement sequence</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Statement sequence</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statement sequence</em>' containment reference.
   * @see #setStatement_sequence(statement_sequence)
   * @see org.xtext.example.pascal.pascal.PascalPackage#getrepeat_statement_Statement_sequence()
   * @model containment="true"
   * @generated
   */
  statement_sequence getStatement_sequence();

  /**
   * Sets the value of the '{@link org.xtext.example.pascal.pascal.repeat_statement#getStatement_sequence <em>Statement sequence</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Statement sequence</em>' containment reference.
   * @see #getStatement_sequence()
   * @generated
   */
  void setStatement_sequence(statement_sequence value);

  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expression</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(expression)
   * @see org.xtext.example.pascal.pascal.PascalPackage#getrepeat_statement_Expression()
   * @model containment="true"
   * @generated
   */
  expression getExpression();

  /**
   * Sets the value of the '{@link org.xtext.example.pascal.pascal.repeat_statement#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(expression value);

} // repeat_statement
