/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.pascal.pascal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>scale factor</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.pascal.pascal.scale_factor#getSign <em>Sign</em>}</li>
 *   <li>{@link org.xtext.example.pascal.pascal.scale_factor#getDigit_sequence <em>Digit sequence</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.pascal.pascal.PascalPackage#getscale_factor()
 * @model
 * @generated
 */
public interface scale_factor extends EObject
{
  /**
   * Returns the value of the '<em><b>Sign</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sign</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sign</em>' attribute.
   * @see #setSign(String)
   * @see org.xtext.example.pascal.pascal.PascalPackage#getscale_factor_Sign()
   * @model
   * @generated
   */
  String getSign();

  /**
   * Sets the value of the '{@link org.xtext.example.pascal.pascal.scale_factor#getSign <em>Sign</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sign</em>' attribute.
   * @see #getSign()
   * @generated
   */
  void setSign(String value);

  /**
   * Returns the value of the '<em><b>Digit sequence</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Digit sequence</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Digit sequence</em>' containment reference.
   * @see #setDigit_sequence(digit_sequence)
   * @see org.xtext.example.pascal.pascal.PascalPackage#getscale_factor_Digit_sequence()
   * @model containment="true"
   * @generated
   */
  digit_sequence getDigit_sequence();

  /**
   * Sets the value of the '{@link org.xtext.example.pascal.pascal.scale_factor#getDigit_sequence <em>Digit sequence</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Digit sequence</em>' containment reference.
   * @see #getDigit_sequence()
   * @generated
   */
  void setDigit_sequence(digit_sequence value);

} // scale_factor
