/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.pascal.pascal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>set</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.pascal.pascal.set#getElement_list <em>Element list</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.pascal.pascal.PascalPackage#getset()
 * @model
 * @generated
 */
public interface set extends EObject
{
  /**
   * Returns the value of the '<em><b>Element list</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Element list</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Element list</em>' containment reference.
   * @see #setElement_list(element_list)
   * @see org.xtext.example.pascal.pascal.PascalPackage#getset_Element_list()
   * @model containment="true"
   * @generated
   */
  element_list getElement_list();

  /**
   * Sets the value of the '{@link org.xtext.example.pascal.pascal.set#getElement_list <em>Element list</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Element list</em>' containment reference.
   * @see #getElement_list()
   * @generated
   */
  void setElement_list(element_list value);

} // set
