/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.pascal.pascal;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>strings</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.pascal.pascal.strings#getString_character <em>String character</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.pascal.pascal.PascalPackage#getstrings()
 * @model
 * @generated
 */
public interface strings extends EObject
{
  /**
   * Returns the value of the '<em><b>String character</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.pascal.pascal.string_character}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>String character</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>String character</em>' containment reference list.
   * @see org.xtext.example.pascal.pascal.PascalPackage#getstrings_String_character()
   * @model containment="true"
   * @generated
   */
  EList<string_character> getString_character();

} // strings
