/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.pascal.pascal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.pascal.pascal.type#getSimple_type <em>Simple type</em>}</li>
 *   <li>{@link org.xtext.example.pascal.pascal.type#getStructured_type <em>Structured type</em>}</li>
 *   <li>{@link org.xtext.example.pascal.pascal.type#getPointer_type <em>Pointer type</em>}</li>
 *   <li>{@link org.xtext.example.pascal.pascal.type#getType_identifier <em>Type identifier</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.pascal.pascal.PascalPackage#gettype()
 * @model
 * @generated
 */
public interface type extends EObject
{
  /**
   * Returns the value of the '<em><b>Simple type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Simple type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Simple type</em>' containment reference.
   * @see #setSimple_type(simple_type)
   * @see org.xtext.example.pascal.pascal.PascalPackage#gettype_Simple_type()
   * @model containment="true"
   * @generated
   */
  simple_type getSimple_type();

  /**
   * Sets the value of the '{@link org.xtext.example.pascal.pascal.type#getSimple_type <em>Simple type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Simple type</em>' containment reference.
   * @see #getSimple_type()
   * @generated
   */
  void setSimple_type(simple_type value);

  /**
   * Returns the value of the '<em><b>Structured type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Structured type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Structured type</em>' containment reference.
   * @see #setStructured_type(structured_type)
   * @see org.xtext.example.pascal.pascal.PascalPackage#gettype_Structured_type()
   * @model containment="true"
   * @generated
   */
  structured_type getStructured_type();

  /**
   * Sets the value of the '{@link org.xtext.example.pascal.pascal.type#getStructured_type <em>Structured type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Structured type</em>' containment reference.
   * @see #getStructured_type()
   * @generated
   */
  void setStructured_type(structured_type value);

  /**
   * Returns the value of the '<em><b>Pointer type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pointer type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pointer type</em>' containment reference.
   * @see #setPointer_type(pointer_type)
   * @see org.xtext.example.pascal.pascal.PascalPackage#gettype_Pointer_type()
   * @model containment="true"
   * @generated
   */
  pointer_type getPointer_type();

  /**
   * Sets the value of the '{@link org.xtext.example.pascal.pascal.type#getPointer_type <em>Pointer type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pointer type</em>' containment reference.
   * @see #getPointer_type()
   * @generated
   */
  void setPointer_type(pointer_type value);

  /**
   * Returns the value of the '<em><b>Type identifier</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type identifier</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type identifier</em>' containment reference.
   * @see #setType_identifier(type_identifier)
   * @see org.xtext.example.pascal.pascal.PascalPackage#gettype_Type_identifier()
   * @model containment="true"
   * @generated
   */
  type_identifier getType_identifier();

  /**
   * Sets the value of the '{@link org.xtext.example.pascal.pascal.type#getType_identifier <em>Type identifier</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type identifier</em>' containment reference.
   * @see #getType_identifier()
   * @generated
   */
  void setType_identifier(type_identifier value);

} // type
