/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.pascal.pascal;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>variable declaration part</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.pascal.pascal.variable_declaration_part#getVariable_declaration <em>Variable declaration</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.pascal.pascal.PascalPackage#getvariable_declaration_part()
 * @model
 * @generated
 */
public interface variable_declaration_part extends EObject
{
  /**
   * Returns the value of the '<em><b>Variable declaration</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.pascal.pascal.variable_declaration}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Variable declaration</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable declaration</em>' containment reference list.
   * @see org.xtext.example.pascal.pascal.PascalPackage#getvariable_declaration_part_Variable_declaration()
   * @model containment="true"
   * @generated
   */
  EList<variable_declaration> getVariable_declaration();

} // variable_declaration_part
